-- Localizar Foreign Key
SELECT
	rc.*
FROM
	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS rc
LEFT OUTER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU1
	ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG
	AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA
	AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME
WHERE
	(KCU1.TABLE_NAME = 'tbGestaoCobrancaBoletoOcorrencia')
AND (rc.CONSTRAINT_NAME = 'FK_tbGestaoCobrancaBoletoOcorrencia_tbGestaoCobrancaBoletoOcorrenciaTipo')